### ISSUE TITLE
chomp and the number zero

### ISSUE THREAD

**Issue by jpcompton** [chaosotter/basic-games#1]
Chomp (MODERN.EXE) will happily accept the number zero for players, rows, and columns.

With zero players, the game seems to run with an unlimited number of players (got up to player 22 before the game ended.)

With zero rows or zero columns, the board is blank and the game unplayable.

**Comment by chaosotter** [comment]
Many of these games have only minimal input-checking in their original
form, and thus far I've paid little attention to making the colorized
versions bulletproof.  However, I've updated Chomp with checks for 0
players, rows, and columns (and updated the version up on the Internet
Archive as well).

Thanks for the report!
